### ISSUE TITLE
POST Request event/propositionEvent

### ISSUE THREAD

**Issue by ThisIsLuckyluck** [ByeByeCanap/ByeByeCanap-API#13]
MissPlaced Token in the body, should be in the header instead of the body.

**Comment by ThisIsLuckyluck** [comment]
Le token une fois récupéré n'est pas dans le body mais dans le "header"

**Comment by Olivia1362** [comment]
Ok je veux bien que tu m'expliques ça

**Comment by ThisIsLuckyluck** [comment]
> Ok je veux bien que tu m'expliques ça

Je t'expliquerais demain je pense que c'est mieux, aujourd'hui on va faire une pause.
