### ISSUE TITLE
POST Request SIGNIN

### ISSUE THREAD

**Issue by ThisIsLuckyluck** [ByeByeCanap/ByeByeCanap-API#15]
Request SignIn doesnt work anymore.
![image](https://github.com/user-attachments/assets/ccdb5c76-f387-473e-af19-d82930971b99)

**Comment by ThisIsLuckyluck** [comment]
Dans l'erreur il cherche une collection "profileInfos" mais dans la DB la collection s'appelle "profileinfos"

**Comment by Olivia1362** [comment]
Je n'avais pas vu ton commentaire (je ne savais où le trouver) je viens de chercher et j'ai compris Mais si on remet profileInfos on a deux collections donc du coup je ne sais pas comment gérer cette erreur - je préfère ne toucher à rien auj

**Comment by ThisIsLuckyluck** [comment]
> Je n'avais pas vu ton commentaire (je ne savais où le trouver) je viens de chercher et j'ai compris Mais si on remet profileInfos on a deux collections donc du coup je ne sais pas comment gérer cette erreur - je préfère ne toucher à rien auj

Pas de souci Olivia on voit ça Lundi.
